version: "3.9"

services:
  db:
    image: postgres:15
    container_name: meta_pg
    environment:
      POSTGRES_DB: meta_db
      POSTGRES_USER: meta_user
      POSTGRES_PASSWORD: meta_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: meta_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: meta_db
      DB_USER: meta_user
      DB_PASSWORD: meta_password
      API_URL: https://jsonplaceholder.typicode.com/users
    command: ["python", "-m", "app.main"]

volumes:
  pgdata:
